### ISSUE TITLE
Orchestrator

### ISSUE THREAD

**Issue by odyslam** [OdysLam/home-urbit#15]
# Orchestrator Spec

## Features
- Serve user dashboard
- Serve device dashboard
- Load new key/pier to Urbit
- Control lifecycle of containers
- serve status of home-urbit
- supply configuration to anchor
- request configuration from API endpoint

## Tasks

- [x] Scaffolding
- [x] Serve static files
- [ ] cli support
- [ ] load key/pier to urbit
- [ ] control container lifecycle
- [ ] serve status
- [ ] supply configuration to anchor
- [ ] integration tests

## next

- implement unit testing for existing functionality
- implement anyhow for actix
- implement proper tracing
- implement cli
